<?php
//function ghsa_main_block_theme($existing, $type, $theme, $path) {
//    return array(
//        'ghsa_main_block_twig' => array(
//        'variables' => array('test_var' => 'babo'),
//    ),
//);
//    $variables = array(
//        'ghsa_main_block' => array(
//            'variables' => array(
//                'source_text' => NULL,
//            ),
//            'template' => 'ghsa_main_block',
//        ),
//    );
//    return $variables;
//}
