<?php
use Drupal\Component\Utility\Html;
use Drupal\Core\Template\Attribute;

// Add your custom theme override functions here.

/**
 * Implements hook_preprocess_block()
 */
function ghsa_foundation_preprocess_block(&$variables) {
}

/**
 * Implements template_preprocess_field().
 */
function ghsa_foundation_preprocess_field(&$variables) {
}

/**
 * Implements template_preprocess_html().
 *
 * Adds additional classes
 */
function ghsa_foundation_preprocess_html(&$variables) {
}

/**
 * Implements template_preprocess_node
 *
 * Add template suggestions and classes
 */
function ghsa_foundation_preprocess_node(&$variables) { 

  $node = \Drupal::routeMatch()->getParameter('node');

  if(in_array($node->id() , array(9) )){
   $variables['content_attributes']['class'][] = "row";
  }
  
}

/**
 * Implements template_preprocess_page
 *
 * Add convenience variables and template suggestions
 */
function ghsa_foundation_preprocess_page(&$variables) {
}

/**
 * Prepares variables for accordion.
 */
function ghsa_foundation_preprocess_views_view(&$variables) {
  $view = $variables['view'];

  if($view->current_display == 'accordion') {
    $handler  = $view->style_plugin;
    // Fetch classes from handler options.
    if ($handler->options['class']) {
      $class = explode(' ', $handler->options['class']);
      $class = array_map('\Drupal\Component\Utility\Html::cleanCssIdentifier', $class);
      if(!in_array('accordion')) {
        $class[] = 'accordion';
      }
    }
    else {
      $class[] = 'accordion';
    }
    $variables['accordion']['attributes'] = new Attribute(array('class' => $class));
    $variables['accordion']['meta'] = 'data-accordion';
    $variables['accordion']['type'] = $handler->options['type'];

    template_preprocess_views_view_unformatted($variables);
  }

  // Add the row class to appropriate places
  $views = ['events', 'issues'];
  if(in_array($view->id(), $views)) {
    $displays = ['three_upcoming_events', 'three_past_events', 'issues_grid', 'featured_resources'];
    if(in_array($view->current_display, $displays)) {
      $variables['row'] = 'row';
    }
  }

}

/**
 * Prepares variables for accordion. This is for the HTML List format in views.
 */
function ghsa_foundation_preprocess_views_view_list(&$variables) {
  static $index = 0;
  $view = $variables['view'];

  if($view->current_display == 'accordion') {
    $variables['panel_id'] = 'panel' . $index;
    if($index == 0) {
      $variables['is_active'] = 'is-active';
    }
    $index++;
  }
}