<?php

/**
 * @file
 * Contains balance_helper.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * List functionality implemented on this module
 */
function balance_helper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.balance_helper':
      $output  = '<h3>' . t('About Balance Interactive helper module:') . '</h3>';
      $output .= '<ul>';
      $output .= '<li>' . t('Creates a "Jump Menus" block') . '</li>';
      $output .= '</ul>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 */
function balance_helper_theme() {
  // Theme for Jump Menus block.
  $theme['jump_menus'] = [
    'variables' => [
      // 'name' => NULL,
      'modulepath' => (drupal_get_path('module', 'balance_helper')),
    ],
    'template' => 'jump-menus',
  ];
  return $theme;
}

/**
 * Implements hook_form_alter().
 * Customize /node/add/file_upload form
 */
function balance_helper_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'balance_helper_jump_menus_form') {
    $form['#attached']['library'][] = 'balance_helper/JumpMenusForm';
  }
}

// /**
//  * Implements hook_form_views_exposed_form_alter().
//  *
//  */
// function balance_helper_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
//   $form['#attached']['library'][] = 'balance_helper/ExposedFilters';
// }
//
