<?php

/**
 * @file
 * Functions to support theming in the GHSA theme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;
use Drupal\taxonomy\Entity\Term;



/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Customize regions
 */
function ghsa_preprocess_region(&$variables) {

	$region = $variables['elements']['#region'];
	$variables['attributes']['class'][] = 'region';
	$variables['attributes']['class'][] = 'region--' . $region;
	//kint($variables['content']);

}

function ghsa_preprocess(&$vars) {
  $vars['theme_path'] = base_path() . drupal_get_path('theme', 'ghsa');
}

/**
 * Implement hook_preprocess_page_title().
 *
 * We want to change the page title for the views.
 */
function ghsa_preprocess_page_title(&$vars) {
  $request = \Drupal::request();
  $params = $request->attributes->all();
  $tid = $params['arg_0'];
  $term = Term::load($tid);
  if($params['view_id'] == 'state_laws_individual_state') {
    $vars['title'] = $term->getName();
  }
  elseif($params['view_id'] == 'state_laws_individual_issue') {
    $vars['title'] = $term->getName();
  }
}

function ghsa_preprocess_views_view(&$vars){
  $request = \Drupal::request();
  $params = $request->attributes->all();
  $tid = $params['arg_0'];
  $term = Term::load($tid);
  if($params['view_id'] == 'state_laws_individual_state' || $params['view_id'] == 'state_laws_individual_issue') {
    $vars['term'] = $term;
    $copy = $term->field_copy_for_state_laws->getValue()[0]['value'];
    $vars['copy'] = empty($copy) ? 'No copy provided yet.' : $copy;
  }
}

function ghsa_preprocess_views_view_table(&$vars){
    $attr = [
        'href' => '#test',
        'role' => 'tab' ,
        'class' => 'accordion-title' ,
        'id' => 'test-heading' ,
        'aria-controls' => 'test'
    ];
    $vars['a_element'] = new Attribute($attr);
//    dsm($vars['rows'][0]['columns']['title']);
//    dsm($vars['title']);
//    $vars['title']='babo';
}


