<?php

/**
 * @file
 * Functions to support theming in the GHSA theme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;



/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Customize regions
 */
function ghsa_preprocess_region(&$variables) {

	$region = $variables['elements']['#region'];
	$variables['attributes']['class'][] = 'region';
	$variables['attributes']['class'][] = 'region--' . $region;
	//kint($variables['content']);

}

function ghsa_preprocess(&$vars) {
  $vars['theme_path'] = base_path() . drupal_get_path('theme', 'ghsa');
}
